---
title: "Practical Machine Learning Project"
author: "Luke Williams"
date: "2022-12-01"
output: html_document
---

**Loading Data and Libraries**

```{r}
library(lattice)
library(ggplot2)
library(caret)
library(kernlab)
library(rattle)
library(corrplot)
set.seed(1234)
```

```{r}
setwd("/Users/lukewilliams/Desktop")
traincsv <- read.csv("pml-training.csv")
testcsv <- read.csv("pml-testing.csv")

dim(traincsv)
dim(testcsv)

```


**Cleaning the Data**
```{r}
traincsv <- traincsv[,colMeans(is.na(traincsv)) < .9]
traincsv <- traincsv[,-c(1:7)]
nvz <- nearZeroVar(traincsv)
traincsv <- traincsv[,-nvz]
dim(traincsv)
inTrain <- createDataPartition(y=traincsv$classe, p=0.7, list=F)
train <- traincsv[inTrain,]
valid <- traincsv[-inTrain,]
```

**Creating and Testing the Models**
```{r}
control <- trainControl(method="cv", number=3, verboseIter=F)

```

**Decision Tree**
```{r}
mod_trees <- train(classe~., data=train, method="rpart", trControl = control, tuneLength = 5)
fancyRpartPlot(mod_trees$finalModel)
pred_trees <- predict(mod_trees, valid)
cmtrees <- confusionMatrix(pred_trees, factor(valid$classe))
cmtrees

```

**Random Forest**
```{r}
mod_rf <- train(classe~., data=train, method="rf", trControl = control, tuneLength = 5)

pred_rf <- predict(mod_rf, valid)
cmrf <- confusionMatrix(pred_rf, factor(valid$classe))
cmrf
```

**Gradient Boosted Trees**
```{r}
mod_gbm <- train(classe~., data=train, method="gbm", trControl = control, tuneLength = 5, verbose = F)

pred_gbm <- predict(mod_gbm, valid)
cmgbm <- confusionMatrix(pred_gbm, factor(valid$classe))
cmgbm
```

**Support Vector Machine**
```{r}
mod_svm <- train(classe~., data=train, method="svmLinear", trControl = control, tuneLength = 5, verbose = F)

pred_svm <- predict(mod_svm, valid)
cmsvm <- confusionMatrix(pred_svm, factor(valid$classe))
cmsvm
```

**Predictions on Test Set**
```{r}
pred <- predict(mod_rf, testcsv)
print(pred)
```

**Appendix**
```{r}
corrPlot <- cor(train[, -length(names(train))])
corrplot(corrPlot, method="color")

plot(mod_trees)

plot(mod_rf)

plot(mod_gbm)


```


